### ISSUE TITLE
ci-preflight is red on committed main after partial cmd/fak wiring

### ISSUE THREAD

**Issue by claude-ai-netra** [anthony-chaudhary/fak#4060]
Observed on 2026-07-10 while landing an unrelated path-scoped Terminal-Bench commit.

Reproduction

    .\fak.exe ci-preflight

Current evidence

The clean committed-tip archive reports six gofmt failures:
- cmd/fak/deepseekbench.go
- cmd/fak/dispatch_graph.go
- internal/adjudicator/shell_dialect_test.go
- internal/ggufload/gguf_mmproj_test.go
- internal/hooks/commitstamp_test.go
- internal/resumemetrics/metrics.go

The clean build also fails in cmd/fak because committed callers reference missing companion definitions, including dispatchtick.WorkShapeForIssue, applyPlacementGate, guardSessionStartManaged, installGuardPiExtension, writeGuardSettingsFileAtomic, and updated fleet lab-readiness fields/signatures. Those companions exist only in peer-dirty/untracked work or have not landed, so a live-tree build can mask the committed-trunk regression.

Done condition

- fak ci-preflight passes from a clean archive of main.
- Every committed caller has its required committed companion implementation; success does not depend on untracked working-tree siblings.
- The six reported files are gofmt-clean.
- A regression witness proves the committed-tip archive, not the live peer-dirty tree.

**Comment by claude-ai-netra** [comment]
Fresh witness (2026-07-10): fak ci-preflight archived committed tip e524f88f9c13 and failed before #4212 can ship. Build errors are half-landed cmd/fak guard/info symbols (guardOperatorDirectedModeWarn, guardOperatorDirectedEffectiveMode, colorizeGuardInfoBlock, infoInputCopyMode, infoViewState.copyMode). The same preflight also reports nine committed gofmt failures: cmd/fak/deepseekbench.go, cmd/fak/dispatch_graph.go, cmd/fak/traj_report_test.go, internal/adjudicator/shell_dialect_test.go, internal/cacheobs/cacheobs_test.go, internal/ggufload/gguf_mmproj_test.go, internal/hooks/commitstamp_test.go, internal/model/vision_encoder_test.go, internal/sessionjournal/sessionjournal.go. This is committed-tip evidence; the literal peer-dirty tree intermittently compiles when the missing untracked siblings are present.

**Comment by anthony-chaudhary** [comment]
Status from a fresh `fak ci-preflight` run on the current committed tip (`7113abee5ea9`):

```
ci-preflight FAILED — committed tip 7113abee5ea9 is red:
  [gofmt-check] 1 file(s) not formatted:
    internal/cachemeta/mooncake_transfer_test.go
```

The **compile** red this issue was filed for ("partial cmd/fak wiring" → undefined symbols) is **no longer reported** — ci-preflight lists only a gofmt-check failure, no build-check failure, so cmd/fak (and the rest of the module) compiles on the committed tip. The originally-named root cause appears resolved.

The only remaining ci-preflight redness is a **gofmt** drift on `internal/cachemeta/mooncake_transfer_test.go`, which is (a) a different failure class than this issue's compile-red, and (b) transient: that file is under active peer churn (`git status`: `D ` staged-deletion + `??` untracked rewrite), so it will self-resolve when the peer lands. The systemic driver — the `GOFMT` gate being advisory so committed gofmt drift keeps re-entering trunk — is now tracked separately by #5326 (format sibling of epic #4142's FC-1).

Not closing this on my own since ci-preflight is still literally red (on the gofmt file); leaving the close call to the owner. If the intent was specifically the cmd/fak compile-red, that condition is met.

**Comment by anthony-chaudhary** [comment]
Fresh clean-clone readback on 2026-08-04 at remote main \

**Comment by anthony-chaudhary** [comment]
Fresh committed-tip readback on 2026-08-04 at `050b8e148295b5cf8a4835071e428cf4f8ef1deb`:

`fak ci-preflight --json` is still red at the gofmt step, now on:

- `internal/compute/capacity_window_test.go`
- `internal/gateway/debug.go`
- `internal/model/contextsize_window_test.go`
- `internal/skillfootprint/skillfootprint.go`

None of these paths was touched by the `421374641e..050b8e1482` git-daily ship range. The clean archive stopped before build, so this issue remains the existing umbrella for restoring a green committed tip; #5326 is the prevention gate.

**Comment by anthony-chaudhary** [comment]
2026-08-08 recurrence while validating unrelated #5891:

fak ci-preflight --skip-build against committed tip 42eb3d719628 failed on these six committed files:
- cmd/fak/route_place_citation_test.go
- internal/compute/capacity_window_test.go
- internal/gateway/events_test.go
- internal/model/contextsize_window_test.go
- internal/modver/regression_test.go
- internal/skillfootprint/skillfootprint.go

This is independently separate from #5993's missing-symbol build failure and from #5891's exact nine-path patch. Done remains the issue's clean committed-archive preflight witness; do not validate against peer-dirty working-tree formatting.

**Comment by anthony-chaudhary** [comment]
Fresh evidence at `origin/main` = `794da8f49d` (2026-08-09), from a clean `git archive` of the committed tip (not the peer-dirty tree):

**Build half: now green.** `go build ./...` in the archive → `BUILD_OK`. The red seen minutes earlier at tip `05f8e32cf5` —

```
cmd/fak/prepush_build.go:277:53: too many arguments in call to runTestQuality
	have (string, io.Writer, io.Writer, nil)
	want (io.Writer, io.Writer, []string)
```

— was repaired on trunk by `794da8f49d fix(quality): repair test-quality call sites (#5936) (fak cmd)`.

**gofmt half: still red, and the file list has rotated off the six named in the body.** `$(go env GOROOT)/bin/gofmt -l .` in the committed-tip archive reports 7:

- `cmd/fak/route_place_citation_test.go`
- `cmd/microcontextdemo/main.go`
- `internal/compute/capacity_window_test.go`
- `internal/gateway/events_test.go`
- `internal/model/contextsize_window_test.go`
- `internal/modver/regression_test.go`
- `internal/skillfootprint/skillfootprint.go`

All 7 are **committed-clean** (`git status --porcelain` on those paths is empty), so this is a committed-blob violation with no peer working-tree edits at risk — `gofmt -w` on exactly those paths is a safe repair, but they span six lanes (`cmd`, `microcontextdemo`, `compute`, `gateway`, `model`, `modver`, `skillfootprint`), so it wants a lane-owner or a deliberate sweep rather than a drive-by from an unrelated issue's commit.

Consequence for workers: `fak ci-preflight` — the verb AGENTS.md names as the answer to "is the committed trunk buildable + gofmt-clean" — exits 1 for **every** agent on this trunk, so it cannot be used as a ship gate until this clears. Rotation of the file list also confirms the body's premise: without the write-boundary gate (#5326 / epic #4142) the set re-populates faster than it is drained.

**Comment by anthony-chaudhary** [comment]
Campaign recheck September 5, 2026: fak-dev ci-preflight --ref HEAD --json at b9931c6c796282a1e0107ff0b25f6023b072f653 returned ok=false. Current failures are gofmt (16 committed files) and study-self-inventory drift; no build failure reported. Captured local receipt: _scratch/astra-ten-ticket-campaign/ci-final.json. This is not a green completion witness. Reconciling existing issue rather than duplicating the committed-trunk gate ticket.

**Comment by anthony-chaudhary** [comment]
Repair scoped to six currently clean, admitted paths: cmd/fak/guard_child_resource.go; internal/compute/cuda_errors_test.go; internal/resumebackoff/resumebackoff_test.go; internal/safesync/{quarantine,safesync}.go; internal/stopgate/doc.go. Persistent astra-format-4060 lease acquired disjoint from seven live leases. Managed formatting worker uses pinned b9931c6c; before/after gofmt witness required. Occupied partitions and inventory remain separate pending work, not a closure claim.

**Comment by anthony-chaudhary** [comment]
Campaign recheck at published e736b90bad2504ad00046c56f3ed74f26b8c7f7f: actual fak-dev ci-preflight --ref HEAD --json exits 1, with 14 gofmt paths and study-self-inventory drift. Local receipt: _scratch/astra-ten-ticket-campaign/ci-current.json. Six-path formatting worker patch is being recovered after managed directory disappeared; no patch has been landed by this campaign. Remaining leased peer paths are untouched.
