### ISSUE TITLE
fix(cuda): seal GDN invalid-state consumers and failure allocations

### ISSUE THREAD

**Issue by anthony-chaudhary** [anthony-chaudhary/fak#4743]
## Parent context
#4738, #4725, and #4714

## Current witness
Commit `39bc7d714cfda07c1d76507a6c7c9b9a4ab22300` (`internal/compute@r123+g39bc7d714`, `internal/model@r298+g39bc7d714`) implements most of the CUDA GDN hardening contract. Independent read-only audit found two remaining implementation defects that block runtime acceptance.

## Work
Make failed GDN state universally unusable across the CUDA backend and reclaim strict whole-operation allocations immediately on every failure path.

- Route every direct CUDA buffer consumer through one shared validity check before pointer submission, including RoPE, AWQ, batched AWQ, GPTQ, and CUDA KV append paths; a buffer invalidated by failed GDN execution must fail typed and never reach another kernel.
- On partial strict-allocation failure or launch/synchronization failure, immediately release/detach every strict output/scratch allocation created by that operation rather than retaining it until a later backend-wide `Recycle`.
- Add deterministic tests that submit invalidated state to representative device consumers and prove typed refusal before launch, plus live/transient allocation-count tests across repeated allocation and async failure injection.
- Keep KV-cache state invalidated and owned for caller cleanup; do not free caller-owned mutable state behind its handle.
- Address any full-CI god-file ratchet caused by the #4738 expansion with a coherent Go-file split inside `internal/compute`, without altering the CUDA ABI or behavior.

## Done when
- Every CUDA operation that can consume a `cudaBuf` rejects `invalid != 0` before pointer submission; focused tests cover direct-consumer bypasses.
- Partial strict-allocation and kernel/synchronization failures return with zero newly retained strict transient allocations, including repeated failure loops.
- Caller-owned convolution/recurrent state remains allocated but invalid and unreadable/unsubmittable until explicitly freed/reinitialized.
- Focused WSL tests, CUDA ABI/type-check/compile matrix, `fak buildcheck --vet`, full committed-tip CI, `fak ci-preflight`, exact-path commit audit, and `origin/main` ancestry pass.
- #4738 and #4725 remain open until separate CPU server corpus and non-skipped DG2 CUDA acceptance are independently witnessed.

## Scope
This child fixes only post-audit CUDA GDN validity/cleanup and any necessary internal/compute file split. It does not implement HAL dispatch, serve preflight, exact-27B serving, or performance work.

## Work estimate
Estimate: 2 points. Uncertainty: direct CUDA consumers have mixed panic/error contracts, so the shared check must preserve their public behavior.

## Overall completion contribution
Contribution: 2/34 points.

## Completion standard
development

**Comment by anthony-chaudhary** [comment]
Headless implementation is active. Parent runtime acceptance remains fail-closed: DG2 is saturated and CPU server minimum per-node reserve is below 4 GiB, so neither lane was run beyond read-only admission probes.

**Comment by anthony-chaudhary** [comment]
Resolved by `c6e3765` (resolving commit). Closed by the DOS dispatch loop's close-resolved arm, witnessed via `dos commit-audit` (verdict OK / diff-witnessed). Reopen if this does not fully resolve it.

**Comment by anthony-chaudhary** [comment]
Independent read-back for `internal/compute@r124+gc6e376542` (`c6e3765426d93fc53e091c8cbbb4ae81d0caa616`):

- Confirmed the commit changes exactly the nine declared `internal/compute` paths and is an ancestor of `origin/main`.
- Confirmed the shared `cudaBufForSubmit` poison check covers RoPE, Q8/Q4, AWQ/batched AWQ, GPTQ, CUDA KV append, collectives, and GDN submission paths before direct pointer use.
- Confirmed strict GDN outputs/scratch are detached from `transient` and freed on allocation or kernel/synchronization failure, while caller-owned conv/recurrent state is invalidated but retained.
- PASS: WSL focused `Qwen35GDN|CUDAInvalid` tests; scoped `fak buildcheck --vet ./internal/compute`; `git show --check`; committed-tip `fak ci-preflight`.
- PASS: hosted CUDA compile run 29386321933, including ABI/type-check and nvcc builds for sm_89/sm_100/sm_120. This is compile-only, not device-runtime evidence.
- Full CI run 29386321931 passed the per-commit build and reached the suite; its main job failed in unrelated `internal/workerworktree.TestLandBaseSHAIsTheDiffRefNotHead` and `internal/workflowaudit.TestLiveDocFresh`, not `internal/compute`; race remained running at this read-back.
- Fresh CPU server admission at 2026-07-15T03:08:58Z refused safely (`min_node_free_mb=1099`, threshold 4096; load1=3.72), so no CPU corpus ran.
- Fresh DG2 read-only probe at 2026-07-15T03:08:51Z still found only 2527-3049 MiB free per accelerator with nine active compute processes, so no disruptive CUDA runtime test ran.

Private transcripts are archived under the existing `fak-private/fleet-runs/qwen36-27b-20260714/4738-validation/{CPU server,dg2}` run tree. Keeping #4743 open because the issue contract includes real-device runtime acceptance; #4738 and #4725 also remain open.

**Comment by anthony-chaudhary** [comment]
Independently read back as shipped on origin/main in c6e3765426d93fc53e091c8cbbb4ae81d0caa616. The exact issue-numbered implementation commit is present on trunk and carries its code/test witness in: internal/compute/cuda.go, internal/compute/cuda_backend.h, internal/compute/cuda_backend_state.go, internal/compute/cuda_collective.go.
